# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDatcubillpayinitiate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_datcubillpayinitiate(self):
    # Test name: datcu bill pay initiate
    # Step # | name | target | value
    # 1 | open | https://online.datcu.org/move-money/pay-bills | 
    self.driver.get("https://online.datcu.org/move-money/pay-bills")
    # 2 | setWindowSize | 1800x1089 | 
    self.driver.set_window_size(1800, 1089)
    # 3 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 4 | click | id=PayeePaymentItems_0__Amount | 
    self.driver.find_element(By.ID, "PayeePaymentItems_0__Amount").click()
    # 5 | type | id=PayeePaymentItems_0__Amount | 1.00
    self.driver.find_element(By.ID, "PayeePaymentItems_0__Amount").send_keys("1.00")
    # 6 | click | css=.hidden-xs > .btn > .fa | 
    self.driver.find_element(By.CSS_SELECTOR, ".hidden-xs > .btn > .fa").click()
    # 7 | mouseOver | css=.hidden-xs > .btn > .fa | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".hidden-xs > .btn > .fa")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | mouseOut | css=.hidden-xs > .btn > .fa | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 9 | click | id=btnSubmitPayment | 
    self.driver.find_element(By.ID, "btnSubmitPayment").click()
    # 10 | click | css=.modal-footer > .pull-left:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > .pull-left:nth-child(2)").click()
    # 11 | mouseOver | css=.modal-footer > .pull-left:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > .pull-left:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | mouseOut | css=.modal-footer > .pull-left:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
