# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNavigatetobillpayscreen():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_navigatetobillpayscreen(self):
    # Test name: navigate to bill pay screen
    # Step # | name | target | value
    # 1 | open | https://online.datcu.org/accounts | 
    self.driver.get("https://online.datcu.org/accounts")
    # 2 | setWindowSize | 1800x1089 | 
    self.driver.set_window_size(1800, 1089)
    # 3 | click | css=.r-vdhdkl | 
    self.driver.find_element(By.CSS_SELECTOR, ".r-vdhdkl").click()
    # 4 | click | css=div:nth-child(2) > .css-175oi2r > .r-13awgt0 | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .css-175oi2r > .r-13awgt0").click()
  
