# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    # Test name: login
    # Step # | name | target | value
    # 1 | open | /web/auth/dashboard | 
    self.driver.get("https://secure.chase.com/web/auth/dashboard")
    # 2 | setWindowSize | 1800x1089 | 
    self.driver.set_window_size(1800, 1089)
    # 3 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 4 | click | id=password | %DXi2tQNld++ZaO
    self.driver.find_element(By.ID, "password").click()
    # 5 | click | id=signin-button | 
    self.driver.find_element(By.ID, "signin-button").click()
  
