# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewtransactionspagetest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_newtransactionspagetest(self):
    # Test name: new transactions page test
    # Step # | name | target | value
    # 1 | click | id=pending-activity-accordion | 
    self.driver.find_element(By.ID, "pending-activity-accordion").click()
    # 2 | click | css=#PENDING-dataTableId-value-row0-column2 > .mds-activity-table__row-value--text | 
    self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row0-column2 > .mds-activity-table__row-value--text").click()
    # 3 | click | css=#PENDING-dataTableId-value-row0-column2 > .mds-activity-table__row-value--text | 
    self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row0-column2 > .mds-activity-table__row-value--text").click()
    # 4 | doubleClick | css=#PENDING-dataTableId-value-row0-column2 > .mds-activity-table__row-value--text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row0-column2 > .mds-activity-table__row-value--text")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 5 | click | css=#PENDING-dataTableId-value-row1-column2 > .mds-activity-table__row-value--text | 
    self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row1-column2 > .mds-activity-table__row-value--text").click()
    # 6 | click | css=#PENDING-dataTableId-value-row1-column2 > .mds-activity-table__row-value--text | 
    self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row1-column2 > .mds-activity-table__row-value--text").click()
    # 7 | doubleClick | css=#PENDING-dataTableId-value-row1-column2 > .mds-activity-table__row-value--text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row1-column2 > .mds-activity-table__row-value--text")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 8 | click | css=#PENDING-dataTableId-value-row2-column2 > .mds-activity-table__row-value--text | 
    self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row2-column2 > .mds-activity-table__row-value--text").click()
    # 9 | click | css=#PENDING-dataTableId-value-row2-column2 > .mds-activity-table__row-value--text | 
    self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row2-column2 > .mds-activity-table__row-value--text").click()
    # 10 | doubleClick | css=#PENDING-dataTableId-value-row2-column2 > .mds-activity-table__row-value--text | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row2-column2 > .mds-activity-table__row-value--text")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 11 | click | css=#PENDING-dataTableId-value-row2-column2 > .mds-activity-table__row-value--text | 
    self.driver.find_element(By.CSS_SELECTOR, "#PENDING-dataTableId-value-row2-column2 > .mds-activity-table__row-value--text").click()
    # 12 | open | https://secure.chase.com/web/auth/dashboard#/dashboard/transactions/1124076097/CARD/BAC | 
    self.driver.get("https://secure.chase.com/web/auth/dashboard#/dashboard/transactions/1124076097/CARD/BAC")
  
